### ISSUE TITLE
when saving console spits An invalid form control with name='' is not focusable.

### ISSUE THREAD

**Issue by NanashiTheNameless** [jlcrochet/inscryption_save_editor#12]
i cant find where it is complaining about, and it wont save

**Comment by jlcrochet** [comment]
This happens if you enter an invalid value somewhere on the form, then switch to another tab and try to save; since there are so many different tabs, it's difficult to find exactly where the invalid value is.

I'm currently working on a better way to handle this issue. For now, you will just have to cycle through each tab and click Save until you find the tab where the invalid value is.

**Comment by jlcrochet** [comment]
I've pushed a change that will cause the form to report errors immediately when navigating away from a tab, so that should help a bit. If you still have problems, please send me a copy of your save file so that I can make sure there isn't anything I'm missing.

**Comment by NanashiTheNameless** [comment]
Thanks very much! I appreciate the rapid support! I’ll keep you posted!
